version: "3.9"
services:
  # K3s kubernetes cluster
  # Lifted from https://github.com/k3s-io/k3s/blob/master/docker-compose.yml
  k3-server:
    image: rancher/k3s:latest
    container_name: k3-server
    command: server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      K3S_TOKEN: token
      K3S_KUBECONFIG_OUTPUT: /output/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: 666
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - .:/output # This is just so that we get the kubeconfig file out
    ports:
      - 6443:6443 # Kubernetes API Server
      - 80:80 # Ingress controller port 80
      - 443:443 # Ingress controller port 443

  k3-agent:
    image: rancher/k3s:latest
    container_name: k3-agent
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      K3S_URL: https://server:6443
      K3S_TOKEN: token

  k3-registry:
    image: registry:latest
    container_name: k3-registry
    ports:
      - 5000:5000
    healthcheck:
      test: "wget -q --spider http://localhost:5000/v2"
      interval: 1s
      timeout: 5s
      retries: 30

volumes:
  k3s-server: {}
