[tool.poetry]
name = "playground"
version = "1.0.0"
description = ""
authors = ["Branch Vincent <branchevincent@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
mkdocs = "^1.1.2"
mkdocs-click = "^0.2.0"
poethepoet = "^0.7.0"
pytest = "^6.0.1"

[tool.poe.tasks]
run = { script = "playground.main:main", help = "Run main" }
lint = { cmd = "true", help = "Run linters and formatters" }
test = { cmd = "true", help = "Run tests" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
