name: Automerge # https://github.com/dependabot/fetch-metadata

on:
  pull_request_target:
    types: [opened, synchronize, labeled, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    # if: github.event.pull_request.user.login == 'dependabot[bot]'
    # if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        run: echo "${{ toJson(github) }}"
      - name: Merge PR
        run: |
          gh pr merge --auto --squash --body="[ci skip]" "$PR_URL"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
