name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - run: echo /home/linuxbrew/.linuxbrew/bin >> $GITHUB_PATH
      - run: brew install bilix
      - run: brew test bilix
