name: CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd: [true, false]
        experimental: [true, false]
    steps:
      - run: ${{ matrix.cmd }}
        continue-on-error: ${{ matrix.experimental }}
      - run: echo final run
      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v2
      #   with:
      #     extra_plugins: |
      #       @semantic-release/changelog
      #       @semantic-release/git
      #   env:
      #     NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - run: npx semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - run: pip install poetry && poetry install
      # - run: |
      #     git config --global user.name "github-actions"
      #     git config --global user.email "action@github.com"
      #     poetry run semantic-release publish
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
