name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: semantic-release publish
