name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - run: git clone --depth=1 https://github.com/fish-shell/fish-shell /tmp/fish
      - run: sudo make -C /tmp/fish install Rust_COMPILER=$(which rustc)
      - run: fish_trace=1 /usr/local/bin/fish -c 'set --show __fish_data_dir'
