name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
      - run: echo /home/linuxbrew/.linuxbrew/bin >> $GITHUB_PATH
      # - run: brew install bilix
      # - run: brew test bilix
      - run: brew config
      - run: brew ls
      - run: brew install shellcheck
      # - run: HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install pkg-config wireshark protobuf
