name: CI
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set node version
        run: echo "::set-env name=NODE_VERSION::$(cat .nvmrc)"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn cache dir
      # - uses: branchvincent/actions/bump@master
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     version-file: pyproject.toml
      #     version-path: tool.poetry.version
