name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install poetry && poetry install
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          poetry run semantic-release publish
