name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sL https://install.python-poetry.org | python
  pipx:
    runs-on: ubuntu-latest
    steps:
      - run: pipx install poetry
