name: Release

on:
  push:
    tags: ["*.*.*"]

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: gh release create ${GITHUB_REF#refs/tags/} -n "Test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    env:
      REPO: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Publish
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t $REPO:${GITHUB_REF#refs/tags/} -t $REPO:latest .
          docker push -a $REPO
