name: Release

on:
  push:
    tags: ["*.*.*"]

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changelog
        run: echo test > .changelog.md
      - name: Create release
        run: gh release create ${GITHUB_REF#refs/tags/} -F .changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    env:
      REPO: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: docker build -t $REPO:${GITHUB_REF#refs/tags/}
      - name: Push
        run: docker push $REPO:${GITHUB_REF#refs/tags/}
